version: "3.7"
services:
  cloudflare-ddns:
    image: wqferan/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /YOUR/PATH/HERE/config.yml:/apps/config.yml
    restart: unless-stopped
